### ISSUE TITLE
Spinner not working

### ISSUE THREAD

**Issue by pensierinmusica** [scottcheng/cropit#132]
Hi,

Thanks for developing this nice plugin! I'm trying to configure it to display the spinner on image loading, as described in the [docs](http://scottcheng.github.io/cropit/).

```css
/* Show load indicator when image is being loaded */
.cropit-image-preview.cropit-image-loading .spinner {
  opacity: 1;
}
```

It doesn't seem to be working though. Is the plugin automatically injecting the needed CSS?

Otherwise maybe we could make the docs a bit more explicit about how to handle these customisations.

Thanks, cheers!
