### ISSUE TITLE
How to manage errors like on demo

### ISSUE THREAD

**Issue by Keenjix** [scottcheng/cropit#141]
Hi,

Thank you so much for your project, it's awesome and really helped me in my work. But I would like to display errors (image too small with outerwidth etc..) like on the demo website. I didn't find any documentation about it.

Can you help me, tell me how did you do ? I'm not a pro with API :$
Thank you !

**Comment by pjb493** [comment]
I'd also like this

**Comment by Keenjix** [comment]
Haha, I tried this afternoon, and got approximately the same code :P 

<script>
$('.image-editor').cropit({
        exportZoom: 1,
        imageBackground: true,
        imageBackgroundBorderWidth: 15,
        allowDragNDrop: true,
        imageState: {
            src: '/core/images/default.jpg',
        },
        onImageError: function(e) {
            if (e.code === 1) {
                $('.cropit-image-preview').find('.error-msg').text("Please use an image that's at least " + $('.cropit-image-preview').outerWidth() + "px in width and " + $('.cropit-image-preview').outerHeight() + "px in height.");
                $('.cropit-image-preview').addClass("has-error")
                    window.setTimeout(function() {
                        return function() {
                            return $('.cropit-image-preview').removeClass("has-error")
                        }
                    }(this), 3e3)
            }
        }
    });
</script>

Difference is I verify the error.code, i don't know if it's right, but it's working actually.
If the author can show us something which is "more official" because right now, it's only some merged codes, not really clean :)

**Comment by sidaurukfreddy** [comment]
Hello i did it but not working, why you configuationnot same like in doc,

**Comment by Keenjix** [comment]
It's just the Jquery part, here the css and html i used like the demo :

```css
.cropit-image-preview .error-msg {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    padding: 10px 20px;
    color: #fff;
    background: rgba(210,65,72,0.8);
    line-height: 1.5;
    opacity: 0;
    -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=0)";
    filter: alpha(opacity=0);
    -webkit-transition: opacity 0.25s;
    -moz-transition: opacity 0.25s;
    -o-transition: opacity 0.25s;
    -ms-transition: opacity 0.25s;
    transition: opacity 0.25s;
}

.cropit-image-preview.has-error .error-msg {
    opacity: 1;
    -ms-filter: none;
    filter: none;
}
```

```html
<div class="cropit-image-preview-container">
        <div class="cropit-image-preview">
        <div class="error-msg"></div>
        </div>
      </div>
```

Hope it'll help you, waiting for the author's help :)
